######################## default configuration ####################
baseURL = "http://blessing.vip"
title = "Blessing For VIPs"
theme = "bigspring-light-hugo"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-4EFT789T40" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true