# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Pantheon Profile"
url = "pantheon/"
weight = 2

[[main]]
name = "Services"
url = "faq/"
weight = 3

[[main]]
name = "Pilgrim’s Path"
url = "example/"
weight = 4

[[main]]
name = "Pricing"
url = "pricing/"
weight = 5

# footer menu left
[[footer_left]]
name = "Pantheon Profiles"
url = "/pantheon"

[[footer_left]]
name = "Miracle Reports"
url = "/miracle-report"

[[footer_left]]
name = "Heavenly FAQs"
url = "faq/"


# footer menu middle
[[footer_middle]]
name = "Services & Pricing"
url = "pricing/"

[[footer_middle]]
name = "Pilgrim’s Path"
url = "example/"

# footer menu right
[[footer_right]]
name = "Spiritual Privacy"
url = "privacy-policy/"

[[footer_right]]
name = "Karma Conditions"
url = "terms-conditions/"
