# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 2

[[main]]
name = "Pricing"
url = "pricing/"
weight = 3

# footer menu left
[[footer_left]]
name = "Pantheon Profiles"
url = "/pantheon"

[[footer_left]]
name = "Miracle Reports"
url = "#"

[[footer_left]]
name = "Heavenly FAQs"
url = "faq/"


# footer menu middle
[[footer_middle]]
name = "Services & Pricing"
url = "pricing/"

[[footer_middle]]
name = "Pilgrim’s Path"
url = "#"

# footer menu right
[[footer_right]]
name = "Spiritual Privacy"
url = "privacy-policy/"

[[footer_right]]
name = "Karma Conditions"
url = "terms-conditions/"
