#################### default parameters ################################
logo = "images/logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "https://cdn.sa.net/2024/05/20/F72RgeoIjqxuPaz.png" # this image will be used as fallback if a page has no image of its own
favicon = "/images/favicon.ico"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Get Started"
link = "pricing"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################

[[social]]
title = "Email"
icon = "fab fa-erlang" # https://fortawesome.com/sets/font-awesome-5-brands
link = "mailto:support@blessing.vip"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "#"